### ISSUE TITLE
Add a House

### ISSUE THREAD

**Issue by saundersdj** [vcu-cmsc355-f17/android-app-tbd#3]
As a roommate
So that I can add my house/apartment as my home
I want to set my home based on the home router

**Comment by nickagliano** [comment]
Given I am on the home page
When I select "Add New House"
Then I should be on the Add New House page
When I press add house by current locaction/wifi
Then I should receive a message saying that my house has been added.

**Comment by nickagliano** [comment]
Given I am on the home page
When I select "Add New House"
Then I should be on the Add New House page
When I press add house by current locaction/wifi
And my phone isn't connected to wifi or location services
Then I should receive a message saying that my house can't be added because location services is turned off.

**Comment by nickagliano** [comment]
Given I am on the home page
When I select "Add New House"
Then I should be on the Add New House page
When I press add house by current locaction/wifi
And my house has already been added/it already exists on my account
Then I should receive a message that says, "This house has already been added!"
